language: node_js
deploy:
  on:
    tags: true
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
script:
  - npm run lint
  - npm run build
  - npm test
  - npm run coverage
  - npm run travis
after_script:
  - npm run coveralls