# 
# Every push to main i will release a new version of this package
# This will run a build, test, and deploy for the package
#
# Created December 5th, 2022
# @author: ywarezk
# @version: 1.2.0
# @license: MIT
# 

name: CI

on:
  push:
    branches:
      - "main"
      
permissions: write-all
jobs:
  deployToBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: |
          npm install
          npm run build
          npm run lint
          npm test
          npm run coverage
          
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "coverage/Icov.info"
          
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          